site_name: cardano-wallet-sign
site_url: https://lambdasistemi.github.io/cardano-wallet-sign/
repo_url: https://github.com/lambdasistemi/cardano-wallet-sign
repo_name: lambdasistemi/cardano-wallet-sign

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: amber
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Development: development.md
